# This is a basic workflow to help you get started with Actions

name: Inject with Theos Jailed
on:
  workflow_dispatch:
    inputs:
      app_url:
        description: "The direct URL to the decrypted ipa"
        default: ""
        required: true
        type: string
      tweak:
        description: "The direct URL to the tweak (satella, spotilife, etc)"
        default: "https://github.com/Paisseon/SatellaJailed/blob/emt/SatellaJailed.dylib?raw=true"
        required: true
        type: string
      app_name:
        description: "App Name"
        default: ""
        required: true
        type: string
      bundle_id:
        description: "Bundle ID (NOT RECOMENDED TO CHANGE)"
        default: ""
        required: true
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build uYouPlus
    runs-on: macos-11
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v3.2.0
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg

      - name: Setup Theos
        uses: actions/checkout@v3.2.0
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive
      
      - name: Caching
        id: SDK
        uses: actions/cache@v3.2.0
        env:
          cache-name: iOS-15.5-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
      
      - name: Download iOS 15.5 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          svn checkout -q https://github.com/chrisharper22/sdks/trunk/iPhoneOS15.5.sdk
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v3.2.0
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Download Tweak & Prepare iPA
        run: |
          curl "https://raw.githubusercontent.com/Muirey03/RemoteLog/master/RemoteLog.h" --output "$THEOS/include/RemoteLog.h"
          curl "${{ env.TWEAK_URL }}" --output "main/Tweak/tweak.deb"
          echo -e "==> Tweak downloaded!"
          wget "$APP_URL" --no-verbose -O main/app.ipa
          echo -e "==> v${{ env.APP_NAME }} downloaded!"
          dpkg-deb -x "main/Tweak/tweak.deb" main/Tweak/tweak/
          unzip -q main/app.ipa -d main/tmp
          rm -rf main/tmp/Payload/app.app/PlugIns/*
          cp -R main/Extensions/*.appex main/tmp/Payload/app.app/PlugIns
        env:
          THEOS: ${{ github.workspace }}/theos
          TWEAK_URL: ${{ inputs.tweak_url }}
          APP_NAME: ${{ inputs.app_name }}
          APP_URL: ${{ inputs.app_url }}

      - name: Fix compiling & Build Package
        id: build_package
        run: |
          (echo 'THEOS_IGNORE_PARALLEL_BUILDING_NOTICE = yes' >> ~/.theosrc)
          cd ${{ github.workspace }}/main
          sed -i '' "12s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
          sed -i '' "11s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile          
          make package FINALPACKAGE=1
          (mv "packages/$(ls -t packages | head -n1)" "packages/${{ env.APP_NAME }}_${{ env.APP_VERSION }}.ipa")
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"
        env:
          THEOS: ${{ github.workspace }}/theos
          APP_VERSION: ${{ inputs.app_version }}
          BUNDLE_ID: ${{ inputs.bundle_id }}
          APP_NAME: ${{ inputs.app_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        env:
          APP_VERSION: ${{ inputs.app_version }}
        with:
          name: ${{ env.APP_NAME }}_${{ env.app_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UYOU_VERSION: ${{ inputs.uyou_version }}
          app_VERSION: ${{ inputs.app_version }}
          DRAFT: ${{ inputs.create_release }}
        with:
          tag_name: v${{ env.APP_NAME }}-(${{ github.run_number }})
          name: v${{ env.APP_NAME }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: ${{ env.DRAFT }}
